# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64ae3c5883f96eb16cb2ad180e1680d2ee77b825964d53717e7ff52b914ab721e282bfc0187e6d821441fa614e3b870ecf3301f8b9c72847b9c5a6a7694ec864

test:
  secret_key_base: b4cfe8ca6f5cd4ea7723aa1840fe681fab4e1866835c85a1ff0f36b3d564f7d4007a3bb9b60c9eb9bfd0c5f61ebcd9b08272bfae5b9f7a3359e2b4ccb38a3b38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
